//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypPromolac
{
    using System;
    using System.Collections.Generic;
    
    public partial class deal
    {
        public int dealsId { get; set; }
        public string dealName { get; set; }
        public double dealPrice { get; set; }
        public double longitude { get; set; }
        public double latitude { get; set; }
        public string dealDescription { get; set; }
        public int dealCategory { get; set; }
        public Nullable<int> vendorId { get; set; }
        public string dealImage { get; set; }
        public string area { get; set; }
        public Nullable<int> adminId { get; set; }
        public System.DateTime dealTime { get; set; }
    
        public virtual dealCategory dealCategory1 { get; set; }
        public virtual mainAdmin mainAdmin { get; set; }
        public virtual vendor vendor { get; set; }
    }
}
