//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypPromolac
{
    using System;
    using System.Collections.Generic;
    
    public partial class fence
    {
        public int fenceId { get; set; }
        public Nullable<int> vendorId { get; set; }
        public double longitude { get; set; }
        public double latitude { get; set; }
        public int radius { get; set; }
        public string notification { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime endTime { get; set; }
        public string area { get; set; }
        public Nullable<int> adminId { get; set; }
    
        public virtual mainAdmin mainAdmin { get; set; }
        public virtual vendor vendor { get; set; }
    }
}
