//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypPromolac
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vendor()
        {
            this.userPackages = new HashSet<userPackage>();
            this.vendor1 = new HashSet<vendor>();
            this.areaAssigneds = new HashSet<areaAssigned>();
            this.deals = new HashSet<deal>();
            this.fences = new HashSet<fence>();
            this.notifications = new HashSet<notification>();
            this.messages_ = new HashSet<messages_>();
        }
    
        public int vendorId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string phoneNumber { get; set; }
        public string vendorEmail { get; set; }
        public string vendorAddress { get; set; }
        public string vendorCompanyName { get; set; }
        public System.DateTime registerTimestamp { get; set; }
        public string vendorUserName { get; set; }
        public string vendorPassword { get; set; }
        public string vendorStatus { get; set; }
        public Nullable<int> vendorAdminId { get; set; }
        public Nullable<int> headId { get; set; }
        public string isHead { get; set; }
    
        public virtual mainAdmin mainAdmin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userPackage> userPackages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vendor> vendor1 { get; set; }
        public virtual vendor vendor2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<areaAssigned> areaAssigneds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deal> deals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fence> fences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notification> notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<messages_> messages_ { get; set; }
    }
}
